baseURL: https://blog.lourenci.com/
languageCode: en-us
title: Lourenci's Notes
theme: default
markup:
  highlight:
    style: github
permalinks:
  posts: /:title/

outputFormats:
  RSS:
    baseName: feed
